# Created with YamlCreate.ps1 v2.5.0 $debug=QUSU.CRLF.7-5-4.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.10.0.schema.json

PackageIdentifier: JRSoftware.InnoSetup.7
PackageVersion: 7.0.0
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.10.0
