# Created with YamlCreate.ps1 v2.5.0 $debug=QUSU.CRLF.7-5-4.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: JRSoftware.InnoSetup.7
PackageVersion: 7.0.0
MinimumOSVersion: 6.1.0.0
InstallerType: inno
FileExtensions:
- iss
RepairBehavior: installer
Installers:
- Architecture: x64
  Scope: machine
  InstallerUrl: https://jrsoftware.org/download.php/innosetup-7.0.0-x64.exe
  InstallerSha256: 4d11e8050b6185e0d49bd9e8cc661a7a59f44959a621d31d11033124c4e8a7b0
  InstallerSwitches:
    Custom: /ALLUSERS
  ProductCode: Inno Setup 7_is1
  AppsAndFeaturesEntries:
  - DisplayName: Inno Setup version 7.0.0
    ProductCode: Inno Setup 7_is1
- Architecture: x64
  Scope: user
  InstallerUrl: https://jrsoftware.org/download.php/innosetup-7.0.0-x64.exe
  InstallerSha256: 4d11e8050b6185e0d49bd9e8cc661a7a59f44959a621d31d11033124c4e8a7b0
  InstallerSwitches:
    Custom: /CURRENTUSER
  ProductCode: Inno Setup 7_is1
  AppsAndFeaturesEntries:
  - DisplayName: Inno Setup version 7.0.0
    ProductCode: Inno Setup 7_is1
- Architecture: x86
  Scope: machine
  InstallerUrl: https://jrsoftware.org/download.php/innosetup-7.0.0-x86.exe
  InstallerSha256: 5d11e8050b6185e0d49bd9e8cc661a7a59f44959a621d31d11033124c4e8a7b0
  InstallerSwitches:
    Custom: /ALLUSERS
  ProductCode: Inno Setup 7 (32-bit)_is1
  AppsAndFeaturesEntries:
  - DisplayName: Inno Setup version 7.0.0 (32-bit)
    ProductCode: Inno Setup 7 (32-bit)_is1
- Architecture: x86
  Scope: user
  InstallerUrl: https://jrsoftware.org/download.php/innosetup-7.0.0-x86.exe
  InstallerSha256: 5d11e8050b6185e0d49bd9e8cc661a7a59f44959a621d31d11033124c4e8a7b0
  InstallerSwitches:
    Custom: /CURRENTUSER
  ProductCode: Inno Setup 7 (32-bit)_is1
  AppsAndFeaturesEntries:
  - DisplayName: Inno Setup version 7.0.0 (32-bit)
    ProductCode: Inno Setup 7 (32-bit)_is1
ManifestType: installer
ManifestVersion: 1.10.0
